server:
  port: 8080

artemis:
  core:
    broker-urls:
      - ssl://127.0.0.1:61617
      - ssl://127.0.0.1:61717
    user: admin
    password: password
    trust-store-path: truststore.p12
    trust-store-password: changeit
    producer-pool-size: 2
    consumer-threads-per-queue: 1
    consumer-mode: ASYNC
    retry-interval: 1000
    retry-interval-multiplier: 1.5
    max-retry-interval: 5000
    reconnect-attempts: 5
    confirmation-window-size: 1024
    queues:
      - exampleQueue1
      - exampleQueue2

logging:
  level:
    root: info
    com.example.artemis: debug
