server:
  port: 8080

artemis:
  jms:
    broker-urls:
      - tcp://127.0.0.1:61617
      - tcp://127.0.0.1:61717
    user: admin
    password: password
    ssl-enabled: true
    trust-store-path: truststore.p12
    trust-store-password: changeit
    max-connections: 2
    max-sessions-per-connection: 10
    producer-pool-size: 2
    consumer-threads-per-queue: 1
    consumer-mode: SYNC
    retry-interval: 1000
    retry-interval-multiplier: 1.5
    max-retry-interval: 5000
    reconnect-attempts: 3
    confirmation-window-size: 1048576
    queues:
      - exampleQueue1
      - exampleQueue2

logging:
  level:
    root: info
    com.example.artemis: debug
